accounts/urls.py
from django.urls import path

from .views import SignUpView, DetailView, DeleteView, UpdateEmailView, ProjectsView

# This file defines the accessible endpoints within the internal app accounts.

app_name = 'accounts'
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),  # sign up view
    path("<int:pk>/delete/", DeleteView.as_view(), name="delete"),  # delete view of specific user
    path("<int:pk>/detail/", DetailView.as_view(), name="detail"),  # details view of specific user
    path("<int:pk>/detail/email", UpdateEmailView.as_view(), name="update_email"),  # update email view of specific user
    path("<int:pk>/projects/", ProjectsView.as_view(), name="projects"),  # projects view of specific user
]

finalProject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from finalProject import settings

urlpatterns = [
    path('nanoer/', include('nanoer.urls')),  # endpoints within nanoer
    path("accounts/", include("accounts.urls")),  # endpoints within accounts
    path("accounts/", include("django.contrib.auth.urls")),  # endpoints within admin related to authorization
    path('', TemplateView.as_view(template_name='home.html'), name='home'),  # website's home page
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),  # website's about page
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nanoer/urls.py
from django.urls import path

from .views import IndexView, CreateView, DetailView, temp_clean_up, get_project_list, save_to_project, DeleteView, \
    delete_confirm, download_analysis, AnalysisUpdateView, AnalysisDeleteView, ProjectUpdateView, download_project

# This file defines the accessible endpoints within the app nanoer.

app_name = 'nanoer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # app's home view
    path('save_to_project', save_to_project, name='save_to_project'),  # save analysis to project
    path('project/create/<int:pk>', CreateView.as_view(), name='create'),  # create new project view
    path('project/<int:pk>', DetailView.as_view(), name='detail'),  # details view of specific project
    path('temp_clean_up', temp_clean_up, name='temp_clean_up'),  # delete temporary files
    path('get_project_list', get_project_list, name='get_project_list'),  # list all projects of specific user
    path('project/<int:pk>/delete', DeleteView.as_view(), name='delete'),  # delete view of specific project
    # delete view of specific analysis
    path('analysis/<int:pk>/delete', AnalysisDeleteView.as_view(), name='delete_analysis'),
    path('<str:model>/<int:pk>/delete_confirm', delete_confirm, name='delete_confirm'),  # confirm model deletion
    path('analysis/<int:pk>/download', download_analysis, name='download_analysis'),  # download analysis' files
    path('project/<int:pk>/download', download_project, name='download_project'),  # download project's files
    # update view of specific analysis
    path('analysis/<int:pk>/edit', AnalysisUpdateView.as_view(), name='edit_analysis'),
    # update view of specific project
    path('project/<int:pk>/edit', ProjectUpdateView.as_view(), name='edit_project'),
]

nanoer/models.py
from django.contrib.auth.models import User
from django.db import models


# This file defines the models that reflect the database's entities.
# Each class is an entity and their properties are the tables' columns.
# Instances of these classes are the database's entries, the tables' rows.
# The relationship between the entities can be basically expressed as:
# [USER]<--1:N-->[PROJECT]<--1:N-->[ANALYSIS]<--1:4-->[FILE]


# Project entity
# One user owns zero or many projects
# One project belongs to only one user
class Project(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.title}: {self.description}, by {self.user}.'


# Analysis entity
# One project owns zero or many analyses
# One analysis belongs to only one project
class Analysis(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title}: {self.description}, from {self.project}'


# File entity
# One analysis owns exactly four files:
#   the original image (TIFF), the processed image (PNG),
#   the size distribution graph (PNG) and the dataframe (CSV)
# One file belongs to only one analysis
class File(models.Model):
    analysis = models.ForeignKey(Analysis, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, default=None, blank=True, null=True)
    uri = models.TextField(max_length=1000, default=None, blank=True, null=True)
    type = models.CharField(max_length=10, default='image', blank=True, null=True)
    source = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, default=None)

    def __str__(self):
        return f'Title: {self.title}' \
               f'URI: {self.uri}' \
               f'Type: {self.type}' \
               f'Source: {self.source}' \
               f'Analysis: {self.analysis}' \
               f'Project: {self.analysis.project}' \
               f'User: {self.analysis.project.user}'

nanoer/views.py
import os
import re
import shutil
import sys
import tempfile

import cv2
import numpy as np
import pandas as pd
import seaborn as sns
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import generic
from django.views.generic import TemplateView
from matplotlib import pyplot as plt
from pytesseract import pytesseract

from finalProject.settings import MEDIA_ROOT, MEDIA_URL
from nanoer.models import Project, File, Analysis


# This file defines all the views in the internal app nanoer.
# The views are classes and functions that respond to web requests with appropriate web responses.
# They invoke the templates that will be rendered in return (if applicable) and handle any errors
# that may arise during the handling of the requests.


# crop uploaded image so that the actual image and the legend
# can be handled separately
def crop_image(img):
    max_y = img.shape[0] - 1  # highest pixel position on the y-axis
    max_x = img.shape[1] - 1  # highest pixel position on the x-axis

    div = max_y

    # from the bottom-right corner up on the legend
    # until it is no longer white, where the legend ends
    for p in range(max_y, 0, -1):
        if np.array_equal(img[p][max_x], [255, 255, 255]):
            div = p
        else:
            break  # div holds the last white pixel position on the y-axis

    image = img[:div, ]  # only the image
    legend = img[div:, int(max_x / 2):]  # only the right-half portion of the legend

    return image, legend


# calculate the factor that each pixel needs to be scaled by
# in order to get the actual size of the nanoparticles (in nanometers)
def calculate_scale(img):  # this image is just the right-half portion of the legend
    max_y = img.shape[0] - 1  # highest pixel position on the y-axis
    max_x = img.shape[1] - 1  # highest pixel position on the x-axis
    x_ref = int(max_x * 1 / 4)  # x-axis reference placed on top of the scale bar

    bar_y = 0

    # from the top of the image, downwards, aligned with x_ref
    # until it is no longer white, where the scale bar starts
    for p in range(max_y):
        if np.array_equal(img[p][x_ref], [255, 255, 255]):
            continue
        else:
            bar_y = p  # y-axis position of the scale bar
            break

    bar_x_left = 0
    bar_x_right = max_x

    # from x_ref, to the left on the x
    # until it becomes white, where the scale bar ends
    for p in range(x_ref, 0, -1):
        if np.any(np.not_equal(img[bar_y][p], [255, 255, 255])):
            bar_x_left = p  # start of the scale bar on the x-axis
        else:
            break

    # from x_ref, to the right on the x
    # until it becomes white, where the scale bar ends
    for p in range(x_ref, max_x):
        if np.any(np.not_equal(img[bar_y][p], [255, 255, 255])):
            bar_x_right = p  # end of the scale bar on the x-axis
        else:
            break

    # size of the scale bar
    bar_size = bar_x_right - bar_x_left

    # using pytesseract (Tesseract OCR for Python) to read text from image
    # the factor is then identified as being any number followed by " nm"
    text = pytesseract.image_to_string(img)
    try:  # tries to read scale factor from image
        factor = int(re.sub(r'[^0-9]', '', re.search(r'[0-9]+ nm', text).group(0)))
    except AttributeError:  # if failed, scale will be 1:1
        factor = bar_size

    return factor / bar_size  # returns scale


# index view of the nanoer app
# any user can submit an image for analysis
# even if they are not logged-in or do not have an account
class IndexView(TemplateView):
    model = Project
    template_name = "nanoer/index.html"
    context_object_name = 'project_list'

    def post(self, request):
        uploaded_file = request.FILES['img']

        # check that the uploaded file is compliant with the required format
        if not hasattr(uploaded_file, 'temporary_file_path') or not uploaded_file.name.lower().endswith(
                ('.tif', '.tiff')):
            return render(request, self.template_name, {'fail': 1})

        path = uploaded_file.temporary_file_path()  # uploaded image
        original_image = cv2.imread(path)  # read uploaded image with OpenCV
        image, legend = crop_image(original_image)  # separate actual from image and legend
        scale = calculate_scale(legend)  # calculate scale from legend

        image = cv2.medianBlur(image, 5)  # blur image to help with edge detection
        gray_img = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)  # make sure image is gray scale

        try:  # tries to process image
            """
            use OpenCV Hough Circle Transform to detect circles. From the official documentation:
            
            cv.HoughCircles(
              image, method, dp, minDist[, circles[, param1[, param2[, minRadius[, maxRadius]]]]]) -> circles
            
            Parameters:
              image=      8-bit, single-channel, grayscale input image.
              circles=    Output vector of found circles. Each vector is encoded as 3 or 4 element 
                          floating-point vector (x,y,radius) or (x,y,radius,votes).
              method=     Detection method, see HoughModes. The available methods are HOUGH_GRADIENT 
                          and HOUGH_GRADIENT_ALT.
              dp=     	  Inverse ratio of the accumulator resolution to the image resolution. For 
                          example, if dp=1 , the accumulator has the same resolution as the input 
                          image. If dp=2 , the accumulator has half as big width and height. For 
                          HOUGH_GRADIENT_ALT the recommended value is dp=1.5, unless some small very 
                          circles need to be detected.
              minDist=    Minimum distance between the centers of the detected circles. If the parameter 
                          is too small, multiple neighbor circles may be falsely detected in addition to 
                          a true one. If it is too large, some circles may be missed.
              param1= 	  First method-specific parameter. In case of HOUGH_GRADIENT and HOUGH_GRADIENT_ALT, 
                          it is the higher threshold of the two passed to the Canny edge detector (the 
                          lower one is twice smaller). Note that HOUGH_GRADIENT_ALT uses Scharr algorithm 
                          to compute image derivatives, so the threshold value shough normally be higher, 
                          such as 300 or normally exposed and contrasty images.
              param2= 	  Second method-specific parameter. In case of HOUGH_GRADIENT, it is the 
                          accumulator threshold for the circle centers at the detection stage. 
                          The smaller it is, the more false circles may be detected. Circles, corresponding 
                          to the larger accumulator values, will be returned first. In the case of 
                          HOUGH_GRADIENT_ALT algorithm, this is the circle "perfectness" measure. 
                          The closer it to 1, the better shaped circles algorithm selects. In most 
                          cases 0.9 should be fine. If you want get better detection of small circles, 
                          you may decrease it to 0.85, 0.8 or even less. But then also try to limit 
                          the search range [minRadius, maxRadius] to avoid many false circles.
              minRadius=  Minimum circle radius.
              maxRadius=  Maximum circle radius. If <= 0, uses the maximum image dimension. If < 0, 
                          HOUGH_GRADIENT returns centers without finding the radius. HOUGH_GRADIENT_ALT 
                          always computes circle radiuses.
            """
            circles = cv2.HoughCircles(image=gray_img, method=cv2.HOUGH_GRADIENT, dp=1, minDist=100, param1=50,
                                       param2=75,
                                       minRadius=25, maxRadius=200)
            circles = np.uint16(np.around(circles))  # round up circle points with numpy

            # back to RGB so that the circles are visible
            color_img = cv2.cvtColor(gray_img, cv2.COLOR_GRAY2RGB)

            # draw the circle outlines and their center points
            for i in circles[0, :]:
                # draw the outer circle
                cv2.circle(color_img, (i[0], i[1]), i[2], (0, 255, 0), 2)
                # draw the center of the circle
                cv2.circle(color_img, (i[0], i[1]), 2, (0, 0, 255), 3)

            # create pandas dataframe from detected circles
            df = pd.DataFrame(data=circles[0], columns=['center_x', 'center_y', 'diameter_nm'])
            # convert radii to nanometers and multiply by 2 to obtain diameter
            df.diameter_nm *= scale * 2

            # prepare canvas and axes to receive graph
            fig, ax = plt.subplots(tight_layout=True)
            ax2 = plt.twinx(ax)  # one x-axis, two y-axes
            ax.set_title('Size Distribution Histogram')
            if scale == 1:  # if scale is 1:1 diameter is in pixels
                ax.set_xlabel('Diameter (px)')
            else:  # else, diameter is in nanometers
                ax.set_xlabel('Diameter (nm)')
            ax.set_ylabel('Number of Particles')
            ax2.set_ylabel('Density')

            # plot histogram with number of particles on the left y-axis
            sns.histplot(data=df, x='diameter_nm', legend=False, color='skyblue', ax=ax)
            # plot KDE with density on the right y-axis
            sns.kdeplot(data=df, x='diameter_nm', legend=False, color='crimson', ax=ax2)

            tmpdir = tempfile.mkdtemp()  # create temporary directory

nanoer/templates/nanoer/create.html
{% extends "base.html" %}

{% block title %}Create New Project{% endblock %}

{% block content %}
    <h1>Create a new project</h1>
    <br><br>
    {# sends a POST request to view associated with the name "create" #}
    <form action="{% url 'nanoer:create' user.id %}" method="post">
        {% csrf_token %}
        <div class="mb-3 form-input-field col-lg-10">
            {# title of the new project #}
            <input type="text" name="title" class="form-control" id="title"
                   placeholder="Title" aria-label="title">
        </div>
        <div class="mb-3 form-input-field col-lg-10">
            {# description of the new project #}
            <textarea name="description" class="form-control" id="description"
                      placeholder="Description" aria-label="description" rows="5"></textarea>
        </div>
        <button class="m-2 btn btn-primary" type="submit">Create</button>
        <a role="button" href="{% url 'accounts:projects' user.id %}" class="m-2 btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

nanoer/templates/nanoer/delete.html
{% extends "base.html" %}

{# model_classname to get replaced by the name of the class of the model #}
{% block title %}{{ model_classname }} Deletion{% endblock %}

{% load static %}
{# loads project's general style sheet #}
<link rel="stylesheet" href="{% static 'style.css' %}">

{% block content %}
    <h1>Delete {{ model_classname }}</h1>
    <br><br>
    <h4>Are you sure that you want to delete the {{ model_classname|lower }} <q>{{ model.title }}</q>?</h4>
    <h4>This action cannot be reversed.</h4>
    <a role="button" href="{{ request.META.HTTP_REFERER }}" class="btn btn-primary mt-5 m-2">Go Back</a>
    <a role="button" href="{% url 'nanoer:delete_confirm' model_classname model.id %}" class="btn btn-danger mt-5 m-2">Confirm</a>
{% endblock %}

nanoer/templates/nanoer/detail.html
{% extends "base.html" %}

{% block title %}Project Details{% endblock %}

{% block content %}
    <h1>{{ context.project.title }}</h1>
    <br>
    <h4>{{ context.project.description }}</h4>
    <br><br>
    {#  list with all analyses that belong to the current project  #}
    {% if context.analysis_list %}
        <div class="row row-cols-3 row-cols-md-2 g-4">
            {# render a Bootstrap card for each analysis in the list #}
            {% for analysis in context.analysis_list %}
                <div class="col">
                    <div class="card text-start h-100">
                        <div class="card-header text-bg-dark">
                            {{ analysis.title }}
                            {# delete current analysis #}
                            <a href="{% url 'nanoer:delete_analysis' analysis.id %}">
                                <i class="fa-solid fa-trash-can text-light little-icon"></i>
                            </a>
                            {# download current analysis #}
                            <a href="{% url 'nanoer:download_analysis' analysis.id %}" download="">
                                <i class="fa-solid fa-download text-light little-icon"></i>
                            </a>
                            {# edit current analysis #}
                            <a href="{% url 'nanoer:edit_analysis' analysis.id %}">
                                <i class="fa-solid fa-pen-to-square text-light little-icon"></i>
                            </a>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ analysis.description }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            {#  list with all files that belong to the current analysis  #}
                            {% for file in context.file_list %}
                                {# filter files by analysis #}
                                {% if file.analysis_id == analysis.id %}
                                    <li class="list-group-item">
                                        {{ file.title }}
                                        {# open current file in a new tab #}
                                        <a href="{{ file.uri }}" target="_blank" rel="noopener noreferrer">
                                            <i class="fa-solid fa-arrow-up-right-from-square text-dark little-icon"></i>
                                        </a>
                                        {% if file.type == "image" %}
                                            <i class="fa-solid fa-file-image right-floater-icon"></i>
                                        {% else %}
                                            <i class="fa-solid fa-file-csv right-floater-icon"></i>
                                        {% endif %}
                                        <br>
                                    </li>
                                {% endif %}
                            {% empty %}
                                <h5>This analysis seems to be empty.</h5>
                            {% endfor %}
                        </ul>
                        <div class="card-footer text-muted">
                            Created at {{ analysis.created_at }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h5>This project is currently empty.</h5>
    {% endif %}
    <br><br>
    <div>
        <div>
            <a role="button" class="btn btn-primary m-2" href="{% url 'accounts:projects' user.id %}">Back to
                Projects</a>
            <a role="button" class="btn btn-primary m-2" href="{% url 'nanoer:index' %}">Run new analysis</a>
        </div>
        <div>
            <a role="button" class="btn btn-secondary m-2" href="{% url 'nanoer:edit_project' context.project.id %}">Edit
                this project</a>
            <a role="button" class="btn btn-secondary m-2" href="{% url 'nanoer:download_project' context.project.id %}"
               download="">Download this project</a>
        </div>
        <div>
            <a role="button" class="btn btn-danger m-2" href="{% url 'nanoer:delete' context.project.id %}">Delete this
                project</a>
        </div>
    </div>
{% endblock %}

nanoer/templates/nanoer/edit_analysis.html
{% extends "base.html" %}

{% block title %}Analysis Update{% endblock %}

{% load static %}
{# loads project's general style sheet #}
<link rel="stylesheet" href="{% static 'style.css' %}">

{% block content %}
    <h1>Update Analysis Details</h1>
    <br><br>
    <h4>Current title: {{ analysis.title }}</h4>
    <h4>Current description: {{ analysis.description }}</h4>
    {# sends a POST request with id from Analysis model instance to view associated with the name "edit_analysis" #}
    <form action="{% url 'nanoer:edit_analysis' analysis.id %}" method="post">
        {% csrf_token %}
        <div class="mt-4 form-input-field">
            <input type="text" name="title" class="form-control" id="exampleFormControlInput1"
                   placeholder="new title" aria-label="title">
        </div>
        <div class="mt-4 form-input-field">
            <textarea name="description" class="form-control" id="exampleFormControlInput1"
                      placeholder="new description" aria-label="description" rows="5"></textarea>
        </div>
        <button class="mt-5 m-1 btn btn-primary" type="submit">Save</button>
        {# passes id from Project model instance to view associated with the name "detail" #}
        <a role="button" href="{% url 'nanoer:detail' analysis.project_id %}"
           class="mt-5 m-1 btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

nanoer/templates/nanoer/edit_project.html
{% extends "base.html" %}

{% block title %}Project Update{% endblock %}

{% load static %}
{# loads project's general style sheet #}
<link rel="stylesheet" href="{% static 'style.css' %}">

{% block content %}
    <h1>Update Project Details</h1>
    <br><br>
    <h4>Current title: {{ project.title }}</h4>
    <h4>Current description: {{ project.description }}</h4>
    {# sends a POST request with id from Project model instance to view associated with the name "edit_project" #}
    <form action="{% url 'nanoer:edit_project' project.id %}" method="post">
        {% csrf_token %}
        <div class="mt-4 form-input-field">
            <input type="text" name="title" class="form-control" id="exampleFormControlInput1"
                   placeholder="new title" aria-label="title">
        </div>
        <div class="mt-4 form-input-field">
            <textarea name="description" class="form-control" id="exampleFormControlInput1"
                      placeholder="new description" aria-label="description" rows="5"></textarea>
        </div>
        <button class="mt-5 m-1 btn btn-primary" type="submit">Save</button>
        {# go back to previous page #}
        <a role="button" href="{{ request.META.HTTP_REFERER }}" class="mt-5 m-1 btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

nanoer/templates/nanoer/index.html
{% extends 'base.html' %}

{% block title %}Run Analysis{% endblock %}

{% block content %}
    <h4>Upload an image file for analysis</h4>
    <p>Learn more about the current file format limitations at <a href="{% url 'about' %}#usage">Usage</a>.</p>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="input-group mb-3 form-file-input-field">
            {# file upload only accepts TIFF format #}
            <input type="file" class="form-control" id="img" name="img" accept=".tif, .tiff">
            <label class="input-group-text" for="img">Upload</label>
        </div>
        <button class="hidden-button mt-4 m-2 btn btn-primary" type="submit">Run
            analysis
        </button>
        <button id="remove-file-button" class="hidden-button mt-4 m-2 btn btn-secondary" type="button">Remove
            file
        </button>
    </form>
    <br>

    {% if fail == 1 %}
        <p class="text-danger">Something is wrong! Please, make sure that you are uploading a TIFF file.</p>
    {% elif fail == 2 %}
        <p class="text-danger">Something went wrong! Unfortunately, we failed to process the uploaded file.</p>
    {% endif %}

    {% if image and chart %}
        <div class="card-group d-flex justify-content-center">
            <div class="card-max-width card">
                <img src="{{ image }}" class="local-card-image card-img-top" alt="...">
                <div class="card-footer">
                    <span class="card-text">Identified Nanoparticles</span>
                    <a href="{{ image }}" target="_blank" rel="noopener noreferrer">
                        <i class="fa-solid fa-arrow-up-right-from-square text-dark little-icon"></i>
                    </a>
                </div>
            </div>
            <div class="card-max-width card">
                <img src="{{ chart }}" class="local-card-image card-img-top" alt="...">
                <div class="card-footer">
                    <span class="card-text">Size Distribution Histogram</span>
                    <a href="{{ chart }}" target="_blank" rel="noopener noreferrer">
                        <i class="fa-solid fa-arrow-up-right-from-square text-dark little-icon"></i>
                    </a>
                </div>
            </div>
        </div>
    {% endif %}
    <br>

    {% if results %}
        {% if user.is_authenticated %}
            {# button trigger modal #}
            <button id="save-to-project" type="button" class="mt-4 m-2 btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">
                Save to project
            </button>
            {# include modal #}
            {% include 'nanoer/save_to_project.html' %}
        {% else %}
            <a role="button" href="{% url 'login' %}" class="mt-4 m-2 btn btn-primary">Save to project</a>
        {% endif %}
        <a class="mt-4 m-2 btn btn-secondary" role="button" href="/media{{ results }}" download="">Download</a>
    {% endif %}

    {% load static %}
    {# loads nanoer's local style sheet #}
    <link rel="stylesheet" href="{% static 'nanoer/style.css' %}">
    {# loads nanoer's local javascript #}
    <script src="{% static 'nanoer/script.js' %}"></script>
    <script>
        {# erase temporary files generated by the last analysis before leaving the page #}
        window.addEventListener("beforeunload", () => {
            console.log("worked")
            tempCleanUp('{{ tmpdir }}', '{% url 'nanoer:temp_clean_up' %}', '{{ csrf_token }}')
        })

        {# toggle Run Analysis and Remove File buttons on/off depending on whether an image has been uploaded #}
        document.getElementById("img").addEventListener("change", (ev) => {
            toggleRunButton(ev.target)
        })

        {# remove file selected for upload from input field and alert the buttons to be toggled #}
        document.getElementById("remove-file-button").addEventListener("click", () => {
            removeFileButton()
        })

        {# get list of projects to be displayed in the modal #}
        document.getElementById("save-to-project").addEventListener("click", () => {
            getProjectList('{% url 'nanoer:get_project_list' %}', '{{ user.id }}')
        })

        {# enable Save button only after one of the radio buttons has been selected #}
        document.getElementById("project-list").addEventListener("change", () => {
            enableSaveButton()
        })

        {# save current analysis to selected project #}
        document.getElementById("save").addEventListener("click", () => {
            saveToProject('{% url 'nanoer:save_to_project' %}', '{{ csrf_token }}', '{{ tmp_files }}')
        })
    </script>
{% endblock %}

nanoer/templates/nanoer/save_to_project.html
{# Bootstrap Modal #}
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-bg-dark">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Choose a project</h1>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="project-list">
                    {# to be populated dynamically #}
                </form>
            </div>
            <div class="modal-footer">
                <button data-bs-dismiss="modal" type="button" id="save" class="btn btn-primary" disabled>Save to
                    project
                </button>
                <a href="{% url 'nanoer:create' user.id %}" role="button" class="btn btn-primary">Create new
                    project</a>
            </div>
        </div>
    </div>
</div>