accounts/urls.py
from django.urls import path

from .views import SignUpView, DetailView, DeleteView, UpdateEmailView, ProjectsView

# This file defines the accessible endpoints within the internal app accounts.

app_name = 'accounts'
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),  # sign up view
    path("<int:pk>/delete/", DeleteView.as_view(), name="delete"),  # delete view of specific user
    path("<int:pk>/detail/", DetailView.as_view(), name="detail"),  # details view of specific user
    path("<int:pk>/detail/email", UpdateEmailView.as_view(), name="update_email"),  # update email view of specific user
    path("<int:pk>/projects/", ProjectsView.as_view(), name="projects"),  # projects view of specific user
]

finalProject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from finalProject import settings

urlpatterns = [
    path('nanoer/', include('nanoer.urls')),  # endpoints within nanoer
    path("accounts/", include("accounts.urls")),  # endpoints within accounts
    path("accounts/", include("django.contrib.auth.urls")),  # endpoints within admin related to authorization
    path('', TemplateView.as_view(template_name='home.html'), name='home'),  # website's home page
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),  # website's about page
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nanoer/urls.py
from django.urls import path

from .views import IndexView, CreateView, DetailView, temp_clean_up, get_project_list, save_to_project, DeleteView, \
    delete_confirm, download_analysis, AnalysisUpdateView, AnalysisDeleteView, ProjectUpdateView, download_project

# This file defines the accessible endpoints within the app nanoer.

app_name = 'nanoer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # app's home view
    path('save_to_project', save_to_project, name='save_to_project'),  # save analysis to project
    path('project/create/<int:pk>', CreateView.as_view(), name='create'),  # create new project view
    path('project/<int:pk>', DetailView.as_view(), name='detail'),  # details view of specific project
    path('temp_clean_up', temp_clean_up, name='temp_clean_up'),  # delete temporary files
    path('get_project_list', get_project_list, name='get_project_list'),  # list all projects of specific user
    path('project/<int:pk>/delete', DeleteView.as_view(), name='delete'),  # delete view of specific project
    # delete view of specific analysis
    path('analysis/<int:pk>/delete', AnalysisDeleteView.as_view(), name='delete_analysis'),
    path('<str:model>/<int:pk>/delete_confirm', delete_confirm, name='delete_confirm'),  # confirm model deletion
    path('analysis/<int:pk>/download', download_analysis, name='download_analysis'),  # download analysis' files
    path('project/<int:pk>/download', download_project, name='download_project'),  # download project's files
    # update view of specific analysis
    path('analysis/<int:pk>/edit', AnalysisUpdateView.as_view(), name='edit_analysis'),
    # update view of specific project
    path('project/<int:pk>/edit', ProjectUpdateView.as_view(), name='edit_project'),
]

accounts/models.py
# Create your models here.

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from nanoer.models import Project, Analysis


# This file defines all the views in the internal app accounts.
# The views are classes and functions that respond to web requests with appropriate web responses.
# They invoke the templates that will be rendered in return (if applicable) and handle any errors
# that may arise during the handling of the requests.


# function to test whether the user making the request is the same one whose details are being requested
def test_func(self):
    return self.request.user.id == self.kwargs['pk']  # true or false


class SignUpView(generic.CreateView):  # sign up view
    model = User  # User instance from models defined by Django
    form_class = UserCreationForm  # UserCreationForm instance from models defined by Django
    success_url = reverse_lazy("login")  # redirect to login page if sing up is successful
    template_name = "registration/signup.html"  # template to be rendered

    def post(self, request, *args, **kwargs):  # handles POST requests
        if request.method == 'POST':
            form = UserCreationForm(request.POST or None)
            if form.is_valid():
                self.model = User.objects.create()  # create an entry in the database for this new user
                self.model.username = request.POST['username']  # set its username from POST
                self.model.email = request.POST['email']  # set its email address from POST
                # set its password from POST, make_password function hashes it, so it's not plain text
                self.model.password = make_password(request.POST['password1'])
                self.model.save()  # save it to database

                # redirects to login page upon successful user creation
                return redirect(self.success_url)
            else:
                fail = 1 if "This field is required" in str(form.errors) else 2
                return render(request, self.template_name, {'form': UserCreationForm(), 'fail': fail})
        else:
            return render(request, self.template_name, {'form': UserCreationForm()})


# details view of specific user
# only logged-in users can access this view
# only users who pass test_func can access this view
class DetailView(LoginRequiredMixin, UserPassesTestMixin, generic.DetailView):
    model = User  # User instance from models defined by Django
    template_name = 'accounts/detail.html'  # template to be rendered

    # tests if user making the request is the same one whose details are being requested
    def test_func(self): return test_func(self)


# delete view of specific user
# only logged-in users can access this view
# only users who pass test_func can access this view
class DeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = User  # User instance from models defined by Django
    template_name = 'accounts/delete.html'  # template to be rendered

    def post(self, request, *args, **kwargs):  # handles POST requests
        self.model = User.objects.get(pk=kwargs['pk'])  # retrieves user from database by id
        if self.model.check_password(request.POST['password']):  # if password matches
            self.model.delete()  # deletes user from database
            return render(request, 'accounts/delete_confirmation.html')  # renders confirmation template
        else:  # if password does not match
            # re-render delete view with error message
            return render(request, self.template_name, context={'fail': 1})

    # tests if user making the request is the same one whose details are being requested
    def test_func(self):
        return test_func(self)


# update email view of specific user
# only logged-in users can access this view
# only users who pass test_func can access this view
class UpdateEmailView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = User  # User instance from models defined by Django
    template_name = 'accounts/change_email.html'  # template to be rendered
    fields = []  # form fields, if applicable

    def post(self, request, *args, **kwargs):  # handles POST requests
        self.model = User.objects.get(pk=kwargs['pk'])  # retrieves user from database by id
        self.model.email = request.POST['email']  # sets its new password
        self.model.save()  # saves to database
        # renders account details view for specific user
        return render(request, 'accounts/detail.html', context={'user': self.model})

    # tests if user making the request is the same one whose details are being requested
    def test_func(self): return test_func(self)


# projects view of specific user
# only logged-in users can access this view
# only users who pass test_func can access this view
class ProjectsView(LoginRequiredMixin, UserPassesTestMixin, generic.ListView):
    model = User  # User instance from models defined by Django
    template_name = 'accounts/projects.html'  # template to be rendered
    context_object_name = 'context'  # context variable to be accessed by the template

    def get_queryset(self):  # returns a list of created projects and a list of created analyses
        # list of projects ordered by most recently updated first
        project_list = Project.objects.filter(user_id=self.kwargs['pk']).order_by('-updated_at')
        # list of analysis that belong to anyone of the projects in project_list
        analysis_list = Analysis.objects.filter(project_id__in=[project.id for project in project_list])

        return {'project_list': project_list, 'analysis_list': analysis_list}  # context

    # tests if user making the request is the same one whose details are being requested
    def test_func(self):
        return test_func(self)

accounts/templates/accounts/change_email.html
{% extends "base.html" %}

{% block title %}Email Update{% endblock %}

{% load static %}
{# loads project's general style sheet #}
<link rel="stylesheet" href="{% static 'style.css' %}">

{% block content %}
    <h1>Change Email</h1>
    <br><br>
    {# email from User model instance #}
    <h4>Current email: {{ user.email }}</h4>
    {# sends a POST request with id from User model instance to view associated with the name "update_email" #}
    <form action="{% url 'accounts:update_email' user.id %}" method="post">
        {% csrf_token %}
        <div class="mt-4 form-input-field">
            <input type="email" name="email" class="form-control" id="exampleFormControlInput1"
                   placeholder="new email address" aria-label="email">
        </div>
        <button class="mt-5 m-1 btn btn-primary" type="submit">Save</button>
        {# passes id from User model instance to view associated with the name "detail" #}
        <a role="button" href="{% url 'accounts:detail' user.id %}" class="mt-5 m-1 btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

accounts/templates/accounts/delete.html
{% extends "base.html" %}

{% block title %}Account Deletion{% endblock %}

{% load static %}
{# loads project's general style sheet #}
<link rel="stylesheet" href="{% static 'style.css' %}">

{% block content %}
    <h1>Delete Account</h1>
    <br><br>
    <h4>Are you sure that you want to delete your user account?</h4>
    <h4>This action cannot be reversed.</h4>
    {# sends a POST request with id from User model instance to view associated with the name "delete" #}
    <form action="{% url 'accounts:delete' user.id %}" method="post">
        {% csrf_token %}
        <div class="mt-4 form-input-field">
            {# shows error message if provided password does not match the one in the database #}
            {% if fail == 1 %}
                <p class="text-danger">Wrong password!</p>
            {% endif %}
            <input type="password" name="password" class="form-control" id="exampleFormControlInput1"
                   placeholder="Password to confirm deletion" aria-label="password">
        </div>
        {# passes id from User model instance to view associated with the name "detail" #}
        <a role="button" href="{% url 'accounts:detail' user.id %}" class="btn btn-primary mt-5 m-2" type="submit">Go
            Back</a>
        <button class="btn btn-danger mt-5 m-2" type="submit">Confirm</button>
    </form>
{% endblock %}

accounts/templates/accounts/delete_confirmation.html
{% extends "base.html" %}

{% block title %}Account Deletion Confirmation{% endblock %}

{% block content %}
    <h1>Accounts</h1>
    <br><br>
    <h4>Your account has been deleted.</h4>
    {# link to view associated with the name "home" #}
    <h4>Return to <a href="{% url 'home' %}">home</a>.</h4>
{% endblock %}

accounts/templates/accounts/detail.html
{% extends "base.html" %}

{% block title %}Account Details{% endblock %}

{% block content %}
    <h1>Account Details</h1>
    <br><br>
    {# username from User model instance #}
    <h4>Username: {{ user.username }}</h4>
    {# email from User model instance #}
    <h4>Email: {{ user.email }}</h4>
    <h4 datatype="password">Password: *********</h4>
    {# passes id from User model instance to view associated with the name "update_email" #}
    <a role="button" href="{% url 'accounts:update_email' user.id %}" class="mt-5 m-1 btn btn-primary">Change email</a>
    {# link to view associated with the name "password_change" #}
    <a role="button" href="{% url 'password_change' %}" class="mt-5 m-1 btn btn-primary">Change password</a>
    <br>
    {# passes id from User model instance to view associated with the name "delete" #}
    <a role="button" href="{% url 'accounts:delete' user.id %}" class="mt-2 btn btn-danger">Delete Account</a>
{% endblock %}

accounts/templates/accounts/projects.html
{% extends "base.html" %}

{% block title %}User Projects{% endblock %}

{% block content %}
    <h1>Projects</h1>
    <br><br>
    {#  list with all projects that belong to the currently logged-in user  #}
    {% if context.project_list %}
        <div class="row row-cols-3 row-cols-md-2 g-4">
            {# render a Bootstrap card for each project in the list #}
            {% for project in context.project_list %}
                <div class="col">
                    <div class="card text-start h-100">
                        <div class="card-header text-bg-dark">
                            {{ project.title }}
                            {# delete current project #}
                            <a href="{% url 'nanoer:delete' project.id %}">
                                <i class="little-icon fa-solid fa-trash-can text-light"></i>
                            </a>
                            {# download current project #}
                            <a href="{% url 'nanoer:download_project' project.id %}" download="">
                                <i class="little-icon fa-solid fa-download text-light"></i>
                            </a>
                            {# edit current project #}
                            <a href="{% url 'nanoer:edit_project' project.id %}">
                                <i class="little-icon fa-solid fa-pen-to-square text-light"></i>
                            </a>
                        </div>
                        <div class="card-body">
                            <p class="card-text">{{ project.description }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            {#  list with all analyses that belong to the currently logged-in user  #}
                            {% for analysis in context.analysis_list %}
                                {# filter analyses by project #}
                                {% if analysis.project_id == project.id %}
                                    <li class="list-group-item">
                                        <b>{{ analysis.title }}:</b> {{ analysis.description }}
                                    </li>
                                {% endif %}
                            {% empty %}
                                <p class="list-group-item">This project seems to be empty.</p>
                            {% endfor %}
                        </ul>
                        <div class="card-footer text-muted">
                            Last updated at {{ project.updated_at }}
                            {# open project #}
                            <a role="button" class="card-footer-button btn btn-primary"
                               href="{% url 'nanoer:detail' project.id %}">Open</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h5>You have not created any projects yet.</h5>
    {% endif %}
    <br>
    {# create new project #}
    <a href="{% url 'nanoer:create' user.id %}" class="m-2 btn btn-primary" role="button">Create a new project</a>
{% endblock %}