accounts/urls.py
from django.urls import path

from .views import SignUpView, DetailView, DeleteView, UpdateEmailView, ProjectsView

# This file defines the accessible endpoints within the internal app accounts.

app_name = 'accounts'
urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),  # sign up view
    path("<int:pk>/delete/", DeleteView.as_view(), name="delete"),  # delete view of specific user
    path("<int:pk>/detail/", DetailView.as_view(), name="detail"),  # details view of specific user
    path("<int:pk>/detail/email", UpdateEmailView.as_view(), name="update_email"),  # update email view of specific user
    path("<int:pk>/projects/", ProjectsView.as_view(), name="projects"),  # projects view of specific user
]

finalProject/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.views.generic import TemplateView

from finalProject import settings

urlpatterns = [
    path('nanoer/', include('nanoer.urls')),  # endpoints within nanoer
    path("accounts/", include("accounts.urls")),  # endpoints within accounts
    path("accounts/", include("django.contrib.auth.urls")),  # endpoints within admin related to authorization
    path('', TemplateView.as_view(template_name='home.html'), name='home'),  # website's home page
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),  # website's about page
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nanoer/urls.py
from django.urls import path

from .views import IndexView, CreateView, DetailView, temp_clean_up, get_project_list, save_to_project, DeleteView, \
    delete_confirm, download_analysis, AnalysisUpdateView, AnalysisDeleteView, ProjectUpdateView, download_project

# This file defines the accessible endpoints within the app nanoer.

app_name = 'nanoer'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),  # app's home view
    path('save_to_project', save_to_project, name='save_to_project'),  # save analysis to project
    path('project/create/<int:pk>', CreateView.as_view(), name='create'),  # create new project view
    path('project/<int:pk>', DetailView.as_view(), name='detail'),  # details view of specific project
    path('temp_clean_up', temp_clean_up, name='temp_clean_up'),  # delete temporary files
    path('get_project_list', get_project_list, name='get_project_list'),  # list all projects of specific user
    path('project/<int:pk>/delete', DeleteView.as_view(), name='delete'),  # delete view of specific project
    # delete view of specific analysis
    path('analysis/<int:pk>/delete', AnalysisDeleteView.as_view(), name='delete_analysis'),
    path('<str:model>/<int:pk>/delete_confirm', delete_confirm, name='delete_confirm'),  # confirm model deletion
    path('analysis/<int:pk>/download', download_analysis, name='download_analysis'),  # download analysis' files
    path('project/<int:pk>/download', download_project, name='download_project'),  # download project's files
    # update view of specific analysis
    path('analysis/<int:pk>/edit', AnalysisUpdateView.as_view(), name='edit_analysis'),
    # update view of specific project
    path('project/<int:pk>/edit', ProjectUpdateView.as_view(), name='edit_project'),
]

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    {% load static %}
    <h1>About the project</h1>
    <br><br>
    <h4>
        <q>automated teeny-tiny-tally</q> (at³) is a web app developed as part of my Research Project/Third Year Project
        at Dorset College BSc in
        Computing, Year 3, Semester 2.
    </h4>
    <br><br>
    <h4 class="text-start">Background</h4>
    <br>
    <h5 class="text-start">
        The aim of this project was to develop a web application that makes use of computer vision to assist
        nanotechnologists in calculating the size distribution of nanoparticle populations by automating the
        analysis of images obtained via TEM and reducing human intervention, thus quickening the
        characterization process and increasing its reliability by removing an error-prone step.
        <br><br>
        You can read more about <a href="https://doi.org/10.1002/9783527648122.ch1" target="_blank">nanoparticles</a>,
        <a
                href="https://doi.org/10.1039/9781782621867-00001" target="_blank">TEM characterization</a> and <a
            href="https://doi.org/10.1007/978-0-387-31439-6" target="_blank">computer vision</a>.
    </h5>
    <br><br>
    <h4 id="usage" class="text-start">Usage</h4>
    <br>
    <h5 class="text-start">
        Input
        <br><br>
        As of now, the application only accepts TIFF files. The uploaded file must be in a very specific visual format
        so that the algorithm can infer the scaling factor when converting from pixels to nanometers by analyzing the
        legend separated from the actual micrograph. You can download a dummy file <a href="{% static 'nanoer/images/dummy_tem_format.tif' %}" download="dummy_tem_format.tif">here</a>.
        <br><br>
        Output
        <br><br>
        The results of each analysis are comprised of four files: the original TIFF image file uploaded by the user; the
        processed image file with the outlined identified nanoparticles, in PNG format; a 3-axis graph with the size
        distribution of the sample represented as both a histogram and a KDE plot; and a CSV file containing the x and y
        coordinates of the center of each nanoparticle, as well as their calculated diameters, in nanometers.
        <br><br>
        User accounts
        <br><br>
        You do not need an account to run as many analysis as you want. After every run, you will have the option to
        download all the artifacts in a ZIP file. That said, users can also create accounts, which allow them
        to create project folders on the server and store/access the results of their analysis remotely. Any stored
        analysis and even whole projects can be downloaded at any time.
    </h5>
    <br><br>
    <h4 class="text-start">Specifications</h4>
    <br>
    <h5 class="text-start">
        This project runs on some juicy <span style="color: green">venom</span>:
        <br><br>
        <ul style="list-style: initial; padding-left: 50px">
            <li><a href="https://opencv.org/" target="_blank">OpenCV</a> (<a
                    href="https://pypi.org/project/opencv-python/"
                    target="_blank">opencv-python</a>)
            </li>
            <li><a href="https://numpy.org/" target="_blank">NumPy</a></li>
            <li><a href="https://pandas.pydata.org/" target="_blank">Pandas</a></li>
            <li><a href="https://seaborn.pydata.org/" target="_blank">Seaborn</a></li>
            <li><a href="https://matplotlib.org/" target="_blank">Matplotlib</a></li>
            <li><a href="https://tesseract-ocr.github.io/" target="_blank">Tesseract OCR</a> (<a
                    href="https://pypi.org/project/pytesseract/" target="_blank">pytesseract</a>)
            </li>
        </ul>
        <br>
        Held together by <a href="https://www.djangoproject.com/" target="_blank">Django</a> and <a
            href="https://www.python.org/" target="_blank">Python</a>.
    </h5>
    <br><br>
    <h5 class="text-start">
        Visit the project's <a href="https://github.com/mateusfonseca/finalProject_Nano_Size_Dist.git"
                               target="_blank">GitHub</a>.
    </h5>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block title %}Base Page{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
          integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    {# loads Bootstrap 5.2.2 style sheet #}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    {# loads Bootstrap 5.2.2 javascript #}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
            crossorigin="anonymous"></script>
    {# loads jQuery library #}
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"
            integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    {% load static %}
    {# loads project's favicon #}
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'images/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'images/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'images/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'images/favicon_io/site.webmanifest' %}">
    {# loads project's general style sheet #}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {# loads project's general javascript #}
    <script src="{% static 'script.js' %}"></script>
</head>
<body>
<nav class="navbar sticky-top navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
        {# link to view associated with the name "home" #}
        <a class="navbar-brand" href="{% url 'home' %}">at³</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    {# link to view associated with the name "index" #}
                    <a class="nav-link active" aria-current="page" href="{% url 'nanoer:index' %}">Run</a>
                </li>
                <li class="nav-item">
                    {# link to view associated with the name "about" #}
                    <a class="nav-link active" aria-current="page" href="{% url 'about' %}">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:projects' user.id %}">Projects</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:detail' user.id %}">Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'logout' %}">Sign Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'login' %}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'accounts:signup' %}">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<main class="container-sm text-center p-5">
    {% block content %}
        {# other templates can extend this one #}
    {% endblock %}
</main>
<footer>
    {% block banner %}
        {# other templates can extend this one #}
    {% endblock %}
    <div class="text-bg-dark footer-text">
        <span>Mateus Fonseca Campos | Dorset College | Dublin | Ireland | 2023</span>
    </div>
</footer>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Welcome to at³</h1>
    <br><br>
    <h3>Choose one of the options below:</h3>
    <br>
    <ul>
        <li><h5><a href="{% url 'nanoer:index' %}">Get started</a></h5></li>
        <li><h5><a href="{% url 'about' %}">About this project</a></h5></li>
        {% if user.is_authenticated %}
            <li><h5><a href="{% url 'logout' %}">Sign out of your account</a></h5></li>
        {% else %}
            <li><h5><a href="{% url 'login' %}">Sign in to your account</a></h5></li>
            <li><h5><a href="{% url 'accounts:signup' %}">Create an account</a></h5></li>
        {% endif %}
    </ul>
{% endblock %}
{% block banner %}
    {% load static %}
    {# loads resource from project's general images directory #}
    <img class="banner-image" src="{% static 'images/home-banner.jpg' %}" alt="music collection">
{% endblock %}